include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_relative_imports: false
    public_member_api_docs: false
    sort_pub_dependencies: false
